//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTemp
    {
        public int Id { get; set; }
        public Nullable<int> TypeTicketId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string NameOfCustomer { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual TypeTicket TypeTicket { get; set; }
    }
}
